### ISSUE TITLE
Authorization endpoint (/authorize) Part 1

### ISSUE THREAD

**Issue by zaki-yama** [zaki-yama/rust-toy-oauth-server#1]
## Summary
Implement authorization endpoint.
The server verifies request parameters and renders a simple UI for the user to grant authorization.

## Tasks

- [ ] verify `response_type`
- [ ] verify `client_id`
- [ ] build simple HTML for user to grant authorization
- [ ] return HTML
