### ISSUE TITLE
Authorization decision endpoint (/

### ISSUE THREAD

**Issue by zaki-yama** [zaki-yama/rust-toy-oauth-server#2]
## Tasks

- [ ] Add a new endpoint (`/approval`, if I follow Google)
- [ ] Implement "Approve" button in the "grant authorization" UI
- [ ] Generate authorization code
- [ ] redirect the user to the URL specified in `redirect_uri`
